### ISSUE TITLE
PyPI owner

### ISSUE THREAD

**Issue by chassing** [ifxit/nidhogg#4]
Hi @rolze (@roolze ),

with your now job, please transfer the ownership of 

* https://pypi.org/project/nidhogg/ 
* https://nidhogg.readthedocs.io/en/master/

to me :)

cheers,
chris

**Comment by rolze** [comment]
added you as owner to the pypi project

what is your rtd account?

**Comment by chassing** [comment]
it's "chassing" (https://readthedocs.org/profiles/chassing/)

**Comment by rolze** [comment]
done. ok, i could have guessed this on my own.... ;)
